# Generated by Django 5.0.1 on 2025-04-14 18:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=10000, upload_to='images/')),
                ('cloudinary_id', models.CharField(blank=True)),
                ('transformation_url', models.URLField(blank=True)),
                ('is_minted_NFT', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransformationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('transformation_type', models.CharField(choices=[('gen_background_replace', 'generative_background'), ('gen_fill', 'generative_fill'), ('enhance', 'enhancement'), ('gen_replace', 'generative_replace'), ('gen_recolor', 'generative_recolor'), ('gen_restore', 'generative_restore'), ('no_trans', 'no_transformation')])),
                ('image_url', models.URLField()),
                ('transformed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transformations', to='imagify.imagemodel')),
                ('transformed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
